// Constants for the Smart Bookmark Extension

// Keyboard shortcuts
var KEYBOARD_SHORTCUT = 'Ctrl+Shift+B';

// Modal element IDs
var MODAL_ID = 'smart-bookmark-modal';
var MODAL_TITLE_ID = 'smart-bookmark-modal-title';
var SEARCH_INPUT_ID = 'smart-bookmark-search';
var FOLDER_LIST_ID = 'smart-bookmark-folder-list';
var BOOKMARK_LIST_ID = 'smart-bookmark-bookmark-list';
var TOAST_ID = 'smart-bookmark-toast';

// CSS classes
var MODAL_ACTIVE_CLASS = 'active';
var FOLDER_ITEM_ACTIVE_CLASS = 'active';
var BOOKMARK_ITEM_ACTIVE_CLASS = 'active';
var TOAST_SHOW_CLASS = 'show';

// Mode classes
var BOOKMARK_SEARCH_MODE_CLASS = 'bookmark-search-mode';
var FOLDER_SELECT_MODE_CLASS = 'folder-select-mode';
var MODE_TRANSITION_CLASS = 'mode-transition';

// Messages
var BOOKMARK_SUCCESS_MESSAGE = '书签添加成功！';
var BOOKMARK_ERROR_MESSAGE = '书签添加失败，请重试。';
var LOADING_FOLDERS_MESSAGE = '正在加载书签文件夹...';
var LOADING_BOOKMARKS_MESSAGE = '正在加载书签...';
var NO_BOOKMARKS_FOUND_MESSAGE = '没有找到书签';
var NO_FOLDERS_FOUND_MESSAGE = '没有找到文件夹';

// Performance
var SEARCH_DEBOUNCE_TIME = 300; // ms
var CACHE_TTL = 5000; // ms

// Default values
var DEFAULT_RECENT_FOLDERS_COUNT = 5;

// Dark mode settings
var DARK_MODE_STORAGE_KEY = 'smart_bookmark_dark_mode';
var DARK_MODE_CLASS = 'dark-mode';
var DARK_MODE_AUTO = 'auto';
var DARK_MODE_LIGHT = 'light';
var DARK_MODE_DARK = 'dark';

// Dark mode toggle element ID
var DARK_MODE_TOGGLE_ID = 'smart-bookmark-dark-mode-toggle';

// Modes
var MODE_BOOKMARK_SEARCH = 'bookmark-search';
var MODE_FOLDER_SELECT = 'folder-select';

// Default mode
var DEFAULT_MODE = MODE_BOOKMARK_SEARCH;

// 将常量附加到全局window对象，以便其他脚本可以访问
window.SMART_BOOKMARK_CONSTANTS = {
  KEYBOARD_SHORTCUT: KEYBOARD_SHORTCUT,
  MODAL_ID: MODAL_ID,
  MODAL_TITLE_ID: MODAL_TITLE_ID,
  SEARCH_INPUT_ID: SEARCH_INPUT_ID,
  FOLDER_LIST_ID: FOLDER_LIST_ID,
  BOOKMARK_LIST_ID: BOOKMARK_LIST_ID,
  TOAST_ID: TOAST_ID,
  MODAL_ACTIVE_CLASS: MODAL_ACTIVE_CLASS,
  FOLDER_ITEM_ACTIVE_CLASS: FOLDER_ITEM_ACTIVE_CLASS,
  BOOKMARK_ITEM_ACTIVE_CLASS: BOOKMARK_ITEM_ACTIVE_CLASS,
  TOAST_SHOW_CLASS: TOAST_SHOW_CLASS,
  BOOKMARK_SEARCH_MODE_CLASS: BOOKMARK_SEARCH_MODE_CLASS,
  FOLDER_SELECT_MODE_CLASS: FOLDER_SELECT_MODE_CLASS,
  MODE_TRANSITION_CLASS: MODE_TRANSITION_CLASS,
  BOOKMARK_SUCCESS_MESSAGE: BOOKMARK_SUCCESS_MESSAGE,
  BOOKMARK_ERROR_MESSAGE: BOOKMARK_ERROR_MESSAGE,
  LOADING_FOLDERS_MESSAGE: LOADING_FOLDERS_MESSAGE,
  LOADING_BOOKMARKS_MESSAGE: LOADING_BOOKMARKS_MESSAGE,
  NO_BOOKMARKS_FOUND_MESSAGE: NO_BOOKMARKS_FOUND_MESSAGE,
  NO_FOLDERS_FOUND_MESSAGE: NO_FOLDERS_FOUND_MESSAGE,
  SEARCH_DEBOUNCE_TIME: SEARCH_DEBOUNCE_TIME,
  CACHE_TTL: CACHE_TTL,
  DEFAULT_RECENT_FOLDERS_COUNT: DEFAULT_RECENT_FOLDERS_COUNT,
  DARK_MODE_STORAGE_KEY: DARK_MODE_STORAGE_KEY,
  DARK_MODE_CLASS: DARK_MODE_CLASS,
  DARK_MODE_AUTO: DARK_MODE_AUTO,
  DARK_MODE_LIGHT: DARK_MODE_LIGHT,
  DARK_MODE_DARK: DARK_MODE_DARK,
  DARK_MODE_TOGGLE_ID: DARK_MODE_TOGGLE_ID,
  MODE_BOOKMARK_SEARCH: MODE_BOOKMARK_SEARCH,
  MODE_FOLDER_SELECT: MODE_FOLDER_SELECT,
  DEFAULT_MODE: DEFAULT_MODE
};

/**
 * 全局辅助函数：获取 Shadow Root
 * 用于在 Shadow DOM 中查找元素，如果 Shadow Root 未初始化则回退到 document
 * @returns {ShadowRoot|Document}
 */
window.getSmartBookmarkRoot = function () {
  return window.smartBookmarkShadowRoot || document;
};